### ISSUE TITLE
Dockerized judgehost can't judge

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#11] opened 2018-03-16 20:05 UTC
After submitting something, verdict is "compiler-error" and output is:

```
Compiling failed with exitcode 255, compiler output:
/opt/domjudge/judgehost/bin/runguard: creating cgroup: Failed to remove a non-empty group(50029)
Try `/opt/domjudge/judgehost/bin/runguard --help' for more information.
Error: failed to set /sys/fs/cgroup/cpuset/domjudge/dj_cgroup_1454_1521230721/cpuset.mems: Permission denied
Error: failed to set /sys/fs/cgroup/cpuset/domjudge/dj_cgroup_1454_1521230721/cpuset.cpus: Permission denied
```

**Comment by SolalPirelli** [comment] 2018-03-16 20:25
@nickygerritsen if you happen to have already seen this, I'd love some insight... otherwise, it can wait, I'll create judgehosts by hand.

**Comment by nickygerritsen** [comment] 2018-03-16 20:27
Are you using Linux? You should enable cgroups on Linux (see the readme). For other OSes it shouldn’t happen and I haven’t seen it happening yet

**Comment by SolalPirelli** [comment] 2018-03-16 20:30
Linux indeed; my `/proc/cmdline` contains `cgroup_enable=memory swapaccount=1` and the machine rebooted after updating GRUB, I think that's all?

**Comment by SolalPirelli** [comment] 2018-03-16 20:31
Found it - need to actually run `/opt/domjudge/judgehost/bin/create_cgroups` in the container. Not sure why it wasn't run.

**Comment by SolalPirelli** [comment] 2018-03-16 20:31
(I'll gladly help fixing this - later, have a contest soon :D)

**Comment by nickygerritsen** [comment] 2018-03-16 20:34
Good luck with the contest. It should run it automatically but we can figure out why it doesn’t.
Thanks for the help!

Could you let us know how the Docker images performed and worked after the contest? I think you are the first to run a contest with it so we are really looking for feedback!

**Comment by greg** [comment] 2018-03-22 02:11
I had the exact same issue with judging. Running the `create_cgroups` command as above fixes it, but if the judgehost container is stopped for whatever reason, it can't be started again:

```
# docker start judgehost-0 -a
[..] Setting timezone

Current default time zone: 'Europe/Amsterdam'
Local time is now:      Thu Mar 22 03:05:22 CET 2018.
Universal Time is now:  Thu Mar 22 02:05:22 UTC 2018.

[ok] Container timezone set to: Europe/Amsterdam

[..] Setting up restapi file
[ok] Restapi file set up

useradd: user 'domjudge-run-0' already exists
```

Deleting the container and setting it up again (including running `create_cgroups`) works, and it's not too much effort since it's only two commands, but still probably not the expected behaviour...

I'll update on how this all performed in my contest in a day or so.

**Comment by nickygerritsen** [comment] 2018-03-22 10:56
I have just pushed a version to Docker Hub that should fix the user creation bug when restarting the container.
This version also contains a possible fix for the `create_cgroups` (see 8696d16). Could you verify it works?

`latest` and `5.3.2` both are updated with these changes.

**Comment by greg** [comment] 2018-03-22 11:06
I can confirm that the `create_cgroups` issue is now fixed, but the user creation error still occurs with the same message. (I've reinstalled both domserver and judgehost on the machine)

**Comment by nickygerritsen** [comment] 2018-03-22 11:37
Ah, typo in my check. I just updated the images again and they should be OK now. Could you please check?

**Comment by greg** [comment] 2018-03-22 12:52
That fixed it, thanks!

**Comment by nickygerritsen** [comment] 2018-03-22 12:53
Great, thanks for testing!

**Closed by nickygerritsen** 2018-03-22 12:53 UTC
Labels: docker
